vich_uploader:
    db_driver: orm
    
    mappings:
        resume:
            uri_prefix: /uploads/resume
            upload_destination: '%kernel.project_dir%/public/uploads/resumes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        coverLetter:
            uri_prefix: /uploads/coverLetter
            upload_destination: '%kernel.project_dir%/public/uploads/coverLetters'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
